In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv('/content/wows_ship_stats.csv')

In [ ]:
df.head(10)

,Ship,Tier,Class,Nation,Players,Battles,Base XP,Damage,Frags,Win rate,Capture,Defence,Spotting,Potential,Aircraft,Survival rate
0,Patrie,11,BB,France,9092,337170,1388,125865,0.936,0.512,2.13,4.74,19358,1809099,5.60,0.426
1,Hannover,11,BB,Germany,16503,319701,1150,86471,0.633,0.485,1.81,4.16,20080,1930510,6.42,0.240
2,Satsuma,11,BB,Japan,40417,1562549,1246,112667,0.809,0.499,1.32,3.21,17402,1730502,4.15,0.469
3,Devastation,11,BB,U.K.,5660,140172,1323,127807,0.766,0.499,1.98,4.78,20776,1896948,4.71,0.499
4,Maine,11,BB,U.S.A.,10744,352970,1344,114812,0.890,0.513,2.32,4.11,22194,2078203,7.70,0.445
5,Admiral Ushakov,11,BB,U.S.S.R.,4355,90980,1293,91532,0.766,0.522,2.71,3.59,23579,2329626,8.86,0.309
6,Sekiryu,11,CV,Japan,5914,144180,1400,140200,1.231,0.518,0.45,8.85,90012,434072,6.18,0.674
7,Eagle,11,CV,U.K.,13166,316332,1355,136724,1.152,0.518,0.35,12.57,83804,380968,5.13,0.671
8,United States,11,CV,U.S.A.,16510,504460,1367,130787,1.095,0.488,0.25,13.26,76674,380087,7.13,0.603
9,Irresistible,10,BB,Commonw.,4391,84046,1310,120722,0.849,0.521,4.01,9.46,16340,1325292,4.83,0.492

In [ ]:
df.isnull().sum()

Ship             0
Tier             0
Class            0
Nation           0
Players          0
Battles          0
Base XP          0
Damage           0
Frags            0
Win rate         0
Capture          0
Defence          0
Spotting         0
Potential        0
Aircraft         0
Survival rate    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 925 entries, 0 to 924
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ship           925 non-null    object
 1   Tier           925 non-null    int64
 2   Class          925 non-null    object
 3   Nation         925 non-null    object
 4   Players        925 non-null    int64
 5   Battles        925 non-null    int64
 6   Base XP        925 non-null    int64
 7   Damage         925 non-null    int64
 8   Frags          925 non-null    float64
 9   Win rate       925 non-null    float64
 10  Capture        925 non-null    float64
 11  Defence        925 non-null    float64
 12  Spotting       925 non-null    int64
 13  Potential      925 non-null    int64
 14  Aircraft       925 non-null    float64
 15  Survival rate  925 non-null    float64
dtypes: float64(6), int64(7), object(3)
memory usage: 115.8+ KB

In [ ]:
df.describe()

,Tier,Players,Battles,Base XP,Damage,Frags,Win rate,Capture,Defence,Spotting,Potential,Aircraft,Survival rate
count,925.000000,925.000000,9.250000e+02,925.000000,925.000000,925.000000,925.000000,925.000000,925.000000,925.000000,9.250000e+02,925.000000,925.000000
mean,7.339459,36561.282162,1.045073e+06,975.094054,49264.187027,0.804107,0.516699,11.309276,8.213459,22148.997838,7.128088e+05,3.689265,0.371503
std,2.342301,48974.272885,1.767742e+06,223.569790,23863.731582,0.384416,0.032881,11.585104,6.976746,17686.419281,4.358737e+05,3.296722,0.116186
min,1.000000,1.000000,1.000000e+00,468.000000,9487.000000,0.384000,0.000000,0.000000,0.000000,143.000000,3.611100e+04,0.000000,0.000000
25%,6.000000,7385.000000,9.483000e+04,822.000000,31164.000000,0.614000,0.499000,3.590000,5.130000,11462.000000,3.723430e+05,1.320000,0.296000
50%,8.000000,17844.000000,3.460050e+05,1008.000000,44287.000000,0.716000,0.513000,5.990000,7.050000,17756.000000,6.162530e+05,3.370000,0.349000
75%,9.000000,47185.000000,1.109821e+06,1139.000000,62895.000000,0.860000,0.531000,15.160000,9.280000,26158.000000,1.026331e+06,5.120000,0.415000
max,11.000000,302858.000000,1.832192e+07,1451.000000,145521.000000,4.906000,0.720000,48.160000,102.370000,120030.000000,2.329626e+06,27.880000,0.830000

In [ ]:
x = df.drop(['Survival rate','Ship','Class','Nation'],axis = 1)
y = df['Survival rate']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
x_train.head()

,Tier,Players,Battles,Base XP,Damage,Frags,Win rate,Capture,Defence,Spotting,Potential,Aircraft
107,9,8727,132467,1131,81302,0.641,0.509,3.16,4.67,18092,1268580,6.63
280,5,56486,1512389,740,38337,0.742,0.522,3.44,4.49,10622,333293,1.59
688,1,60029,139574,534,10950,1.824,0.520,1.83,13.85,684,80421,0.00
375,10,4567,198304,1167,70213,0.853,0.537,23.57,3.44,46449,584497,0.07
665,3,11582,47406,738,42867,1.938,0.503,5.64,30.70,1766,315925,0.05

In [ ]:
x_train.shape

(740, 12)

In [ ]:
# Using Standard Scaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[ 0.67529858, -0.58084805, -0.52817522, ..., -0.2494831 ,
         1.22864339,  0.86877778],
       [-1.0598436 ,  0.38785185,  0.24113756, ..., -0.66104751,
        -0.89282938, -0.65124812],
       [-2.79498579,  0.45971483, -0.52421304, ..., -1.20858795,
        -1.46640846, -1.1307801 ],
       ...,
       [ 0.24151303, -0.24388514, -0.44746585, ..., -0.46970036,
        -0.01307167,  1.53228115],
       [ 0.24151303, -0.50046618, -0.5264503 , ..., -0.66336153,
        -0.11149141,  0.40432542],
       [ 0.24151303,  2.17919315,  4.4687614 , ..., -0.48463128,
         0.48535093,  0.35003878]])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

best_score = float('-inf')
best_k = 0

for i in range(1, 30, 2):
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(x_train, y_train)

    y_pred = knn.predict(x_test)

    score = r2_score(y_test, y_pred)

    print(f'K = {i} : R² Score = {score:.4f}')

    if score > best_score:
        best_score = score
        best_k = i

print("\nBest K:", best_k)
print("Best R² Score:", round(best_score, 4))

K = 1 : R² Score = 0.6874
K = 3 : R² Score = 0.8151
K = 5 : R² Score = 0.7931
K = 7 : R² Score = 0.7847
K = 9 : R² Score = 0.7829
K = 11 : R² Score = 0.7826
K = 13 : R² Score = 0.7728
K = 15 : R² Score = 0.7677
K = 17 : R² Score = 0.7590
K = 19 : R² Score = 0.7462
K = 21 : R² Score = 0.7308
K = 23 : R² Score = 0.7250
K = 25 : R² Score = 0.7131
K = 27 : R² Score = 0.7013
K = 29 : R² Score = 0.6924

Best K: 3
Best R² Score: 0.8151