In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/play_tennis.csv')

In [ ]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [ ]:
df = df.drop('day',axis = 1)

In [ ]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [ ]:
df.shape

(14, 5)

In [ ]:
# problem 1

# outlook-sunny ,Tem = hot, Humidity = high , wind = weak
# play or not play

In [ ]:
# Solution

# p(yea | sunny,hot,high,weak) = p(sunny | yes) * p(hot | yes) * p(high | yes) * p(weak | yes) * p(yes)

# p(No | sunny,hot,high,weak) = p(sunny | No) * p(hot | No) * p(high | No) * p(weak | No) * p(No)

# Campare and decide using the maximum a posteriori rule

In [ ]:
# Problem 2

# outlook = overcast , Temp = Cold , Humidity = Low , Wind = Weak
# Play or not

In [ ]:
# Solution

# p(yes | overcast,Cold,Low,Weak) = p(overcast | yes) * p(Cold | yes) * p(Low | yes) * p(Weak | yes) * p(yes)

# p(No | overcast,Cold,Low,Weak) = p(overcast | No) * p(Cold | No) * p(Low | No) * p(Weak | No) * p(No)

# Campare and decide using the maximum a posteriori rule

In [ ]:
# Training

# Lookup Table (Dictionry)

# Testing

In [ ]:
# p(Yes)
# p(No)

In [ ]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py = 9/14
pn = 5/14

In [ ]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [ ]:
# Outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [ ]:
# temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pcn = 1/5
phn = 2/5
pmn = 2/5

pcy = 3/9
phy = 2/9
pmy = 4/9

In [ ]:
# humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
phighno = 4/5
pnormalno = 1/5

phighyes = 3/9
pnormalyes = 6/9

In [ ]:
# wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
pstongn = 3/5
pweakn = 2/5

pstongy = 3/9
pweaky = 6/9

In [ ]:
# outlook = sunny, Temmp = Hot , Humidity = High , Wind = Weak

pyes = py * phy * pweaky * phighyes * psy
pno = pn * phn * pweakn * phighno * psn

print(pyes)
print(pno)

0.007054673721340388
0.027428571428571438

In [ ]:
# No play in this day

# Sklearn

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [ ]:
df.columns

Index(['outlook', 'temp', 'humidity', 'wind', 'play'], dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
ohe = OneHotEncoder()

lecols = ['temp','outlook']
onecols = ['humidity','wind']

for i in df.columns:
  if df[i].dtype in lecols:
    x_train[i] = le.fit(x_train[i])
    x_test[i] = le.fit_transform(x_test[i])
    print(x_train)
    print('\n')

  elif df[i].dtype in onecols:
    x_train[i] = ohe.fit(x_train[i])
    x_test[i] = ohe.fit_transform(x_test[i])
    print(x_train)

  else:
    pass

In [ ]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6666666666666666
[[1 0]
 [1 1]]
              precision    recall  f1-score   support

          No       0.50      1.00      0.67         1
         Yes       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3